from data_models import NigerianRecipe, QuickRecipe, Recipe


# =========================
# SUBSTITUTE SYSTEM
# =========================
class SubstituteFinder:
    def __init__(self):
        self.substitutes = {
            "rice": ["pasta", "couscous", "quinoa"],
            "chicken": ["beef", "fish", "tofu", "egg"],
            "beef": ["chicken", "turkey", "mushrooms"],
            "fish": ["chicken", "shrimp", "tofu"],
            "egg": ["tofu", "banana", "yogurt"],
            "milk": ["soy milk", "almond milk", "powdered milk"],
            "butter": ["margarine", "vegetable oil", "coconut oil"],
            "flour": ["corn flour", "oat flour", "semolina"],
            "tomato": ["tomato paste", "red bell pepper", "canned tomatoes"],
            "onion": ["spring onion", "garlic", "leek"],
            "garlic": ["garlic powder", "onion", "ginger"],
            "cheese": ["yogurt", "cream", "nutritional yeast"],
            "bread": ["tortilla", "flatbread", "crackers"],
            "pasta": ["noodles", "rice", "spaghetti"],
            "potato": ["yam", "sweet potato", "plantain"],
            "vegetable oil": ["palm oil", "olive oil", "butter"],
            "pepper": ["chilli powder", "paprika", "cayenne pepper"],
            "beans": ["lentils", "chickpeas", "peas"],
            "palm oil": ["vegetable oil", "groundnut oil", "coconut oil"],
            "garri": ["semovita", "pounded yam flour", "wheat flour"],
            "yam": ["potato", "sweet potato", "plantain"],
            "plantain": ["yam", "potato", "sweet potato"],
            "egusi": ["groundnut paste", "ogbono", "melon seed powder"],
            "ogbono": ["egusi", "okra", "groundnut paste"],
            "okra": ["ogbono", "ewedu", "spinach"],
            "ugu": ["spinach", "green amaranth", "scent leaf"],
            "spinach": ["ugu", "green amaranth", "kale"],
            "crayfish": ["stockfish", "dried fish", "shrimp powder"],
            "stockfish": ["dried fish", "crayfish", "smoked fish"],
            "dried fish": ["stockfish", "smoked fish", "crayfish"],
            "iru": ["ogiri", "dawadawa", "crayfish"],
            "coconut milk": ["milk", "cream", "blended coconut"],
            "semovita": ["garri", "wheat flour", "pounded yam flour"],
            "pounded yam flour": ["semovita", "garri", "wheat flour"],
        }

    def find_substitutes(self, ingredient_name):
        ingredient_name = ingredient_name.lower().strip()
        return self.substitutes.get(ingredient_name, ["No substitute found"])


# =========================
# RECIPE DATABASE
# =========================
def create_recipe_database():
    # =========================
    # RECIPE DATABASE
    # =========================
    return [
        Recipe(
            "Chicken Fried Rice",
            ["rice", "chicken", "carrot", "peas", "onion", "egg", "vegetable oil"],
            [
                "Boil the rice until it is almost soft.",
                "Fry onion, carrot, peas, and chicken in vegetable oil.",
                "Add the cooked rice and stir everything together.",
                "Add beaten egg and stir until well cooked.",
                "Serve hot.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        QuickRecipe(
            "Tomato Pasta",
            ["pasta", "tomato", "onion", "garlic", "vegetable oil", "pepper"],
            [
                "Boil the pasta until soft.",
                "Fry onion and garlic in vegetable oil.",
                "Add tomato and pepper, then cook into a sauce.",
                "Mix the pasta with the sauce.",
                "Serve warm.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        QuickRecipe(
            "Bread Omelette",
            ["bread", "egg", "onion", "tomato", "pepper", "vegetable oil"],
            [
                "Beat the eggs in a bowl.",
                "Add chopped onion, tomato, and pepper.",
                "Fry the egg mixture in a little oil.",
                "Place the omelette inside or beside the bread.",
                "Serve for breakfast.",
            ],
            "Breakfast",
            "Easy",
        ),
        NigerianRecipe(
            "Beans Porridge",
            ["beans", "onion", "pepper", "palm oil", "salt"],
            [
                "Wash and boil the beans until soft.",
                "Add chopped onion and pepper.",
                "Add palm oil and salt.",
                "Cook until thick and tasty.",
                "Serve hot.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        QuickRecipe(
            "Potato and Egg Sauce",
            ["potato", "egg", "tomato", "onion", "pepper", "vegetable oil"],
            [
                "Boil the potatoes until soft.",
                "Fry onion, tomato, and pepper in vegetable oil.",
                "Add beaten eggs and stir gently.",
                "Serve the egg sauce with the boiled potatoes.",
            ],
            "Breakfast/Lunch",
            "Easy",
        ),
        QuickRecipe(
            "Vegetable Rice",
            ["rice", "carrot", "peas", "onion", "pepper", "vegetable oil"],
            [
                "Boil the rice until almost done.",
                "Fry onion, carrot, peas, and pepper in vegetable oil.",
                "Add rice and mix well.",
                "Allow it to steam for a few minutes.",
                "Serve hot.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        QuickRecipe(
            "Chicken Sandwich",
            ["bread", "chicken", "tomato", "onion", "butter"],
            [
                "Cook and shred the chicken.",
                "Spread butter on the bread.",
                "Add chicken, tomato, and onion.",
                "Cover with another slice of bread.",
                "Serve as a snack or light meal.",
            ],
            "Snack",
            "Easy",
        ),
        QuickRecipe(
            "Simple Pancakes",
            ["flour", "egg", "milk", "butter", "sugar"],
            [
                "Mix flour, egg, milk, sugar, and melted butter.",
                "Stir until the batter is smooth.",
                "Pour small amounts into a hot pan.",
                "Cook both sides until golden brown.",
                "Serve with tea or syrup.",
            ],
            "Breakfast",
            "Easy",
        ),
        NigerianRecipe(
            "Nigerian Jollof Rice",
            ["rice", "tomato", "pepper", "onion", "vegetable oil", "chicken", "seasoning"],
            [
                "Blend tomato, pepper, and onion.",
                "Fry the mixture in vegetable oil until the sauce thickens.",
                "Add seasoning, chicken stock, and washed rice.",
                "Cook on low heat until the rice is soft.",
                "Serve with chicken.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Egusi Soup",
            ["egusi", "palm oil", "ugu", "crayfish", "stockfish", "pepper", "onion"],
            [
                "Heat palm oil and fry chopped onion.",
                "Add blended egusi and stir until it begins to cook.",
                "Add stockfish, crayfish, pepper, and seasoning.",
                "Add ugu leaves and simmer for a few minutes.",
                "Serve with garri, semovita, or pounded yam.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Ogbono Soup",
            ["ogbono", "palm oil", "crayfish", "stockfish", "pepper", "ugu", "salt"],
            [
                "Mix ground ogbono with palm oil.",
                "Add hot stock and stir until it becomes thick.",
                "Add crayfish, stockfish, pepper, and salt.",
                "Add ugu leaves and cook briefly.",
                "Serve with swallow.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Okra Soup",
            ["okra", "palm oil", "crayfish", "fish", "pepper", "onion", "salt"],
            [
                "Chop the okra into small pieces.",
                "Boil fish with onion, pepper, and salt.",
                "Add palm oil and crayfish.",
                "Add okra and cook for a short time.",
                "Serve with garri or semovita.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Efo Riro",
            ["spinach", "palm oil", "tomato", "pepper", "onion", "crayfish", "fish"],
            [
                "Blend tomato, pepper, and onion.",
                "Fry the mixture in palm oil.",
                "Add crayfish and fish.",
                "Add chopped spinach and stir well.",
                "Cook until the vegetable softens.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Moi Moi",
            ["beans", "pepper", "onion", "vegetable oil", "egg", "fish", "salt"],
            [
                "Peel and blend beans with pepper and onion.",
                "Mix with vegetable oil, salt, fish, and egg.",
                "Pour into containers or leaves.",
                "Steam until firm.",
                "Serve alone or with rice.",
            ],
            "Breakfast/Lunch",
            "Hard",
        ),
        NigerianRecipe(
            "Akara",
            ["beans", "pepper", "onion", "salt", "vegetable oil"],
            [
                "Peel and blend beans with pepper and onion.",
                "Add salt and mix until fluffy.",
                "Heat vegetable oil.",
                "Scoop the mixture into the oil and fry until golden brown.",
                "Serve with pap, bread, or garri.",
            ],
            "Breakfast",
            "Medium",
        ),
        NigerianRecipe(
            "Yam Porridge",
            ["yam", "palm oil", "pepper", "onion", "crayfish", "fish", "salt"],
            [
                "Peel and cut the yam into cubes.",
                "Boil yam with onion, pepper, and salt.",
                "Add palm oil, crayfish, and fish.",
                "Cook until the yam becomes soft and slightly thick.",
                "Serve hot.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Plantain Porridge",
            ["plantain", "palm oil", "pepper", "onion", "crayfish", "fish", "ugu"],
            [
                "Peel and cut the plantain into pieces.",
                "Boil with onion, pepper, and seasoning.",
                "Add palm oil, crayfish, and fish.",
                "Add ugu leaves and cook until soft.",
                "Serve warm.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Ofada Rice and Sauce",
            ["rice", "pepper", "onion", "palm oil", "iru", "egg", "beef"],
            [
                "Boil the rice until soft.",
                "Bleach palm oil lightly and fry onion, pepper, and iru.",
                "Add beef, boiled egg, and seasoning.",
                "Cook the sauce until thick.",
                "Serve the sauce with rice.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Coconut Rice",
            ["rice", "coconut milk", "pepper", "onion", "carrot", "chicken", "vegetable oil"],
            [
                "Wash the rice and set it aside.",
                "Fry onion and pepper in vegetable oil.",
                "Add coconut milk, chicken stock, and rice.",
                "Cook until the rice is soft.",
                "Add carrot and serve.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Pepper Soup",
            ["fish", "pepper", "onion", "scent leaf", "seasoning", "salt"],
            [
                "Wash the fish and place it in a pot.",
                "Add pepper, onion, seasoning, and salt.",
                "Add water and cook until the fish is done.",
                "Add scent leaf near the end.",
                "Serve hot.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Nigerian Suya",
            ["beef", "pepper", "groundnut", "salt", "vegetable oil", "onion"],
            [
                "Slice beef into thin strips.",
                "Coat the beef with groundnut spice, pepper, salt, and oil.",
                "Grill or pan-fry until cooked.",
                "Serve with sliced onion.",
            ],
            "Snack/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Nkwobi",
            ["beef", "palm oil", "pepper", "onion", "ugu", "seasoning", "salt"],
            [
                "Boil beef until soft.",
                "Mix palm oil with pepper, seasoning, and salt.",
                "Add the cooked beef and stir well.",
                "Garnish with onion and ugu.",
                "Serve warm.",
            ],
            "Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Banga Soup",
            ["palm nut extract", "fish", "crayfish", "pepper", "onion", "scent leaf", "salt"],
            [
                "Boil palm nut extract with onion and pepper.",
                "Add fish, crayfish, and seasoning.",
                "Cook until the soup thickens.",
                "Add scent leaf near the end.",
                "Serve with starch, rice, or swallow.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Afang Soup",
            ["afang leaf", "waterleaf", "palm oil", "crayfish", "stockfish", "pepper", "salt"],
            [
                "Cook stockfish with pepper and salt.",
                "Add palm oil and crayfish.",
                "Add waterleaf and cook briefly.",
                "Add afang leaf and stir well.",
                "Serve with swallow.",
            ],
            "Lunch/Dinner",
            "Hard",
        ),
        NigerianRecipe(
            "Ewedu Soup",
            ["ewedu", "iru", "crayfish", "salt", "pepper"],
            [
                "Wash and boil the ewedu leaves.",
                "Blend or mash the leaves until smooth.",
                "Add iru, crayfish, pepper, and salt.",
                "Cook briefly and serve with stew and swallow.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Tuwo Shinkafa",
            ["rice", "water", "salt"],
            [
                "Boil rice with enough water until very soft.",
                "Mash the rice while cooking.",
                "Stir until it becomes smooth and thick.",
                "Mould into balls and serve with soup.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Masa",
            ["rice", "yeast", "sugar", "salt", "vegetable oil"],
            [
                "Soak and blend rice into a smooth batter.",
                "Add yeast, sugar, and salt.",
                "Allow the batter to rise.",
                "Fry small portions in a masa pan or normal pan.",
                "Serve with soup or pepper sauce.",
            ],
            "Breakfast/Snack",
            "Medium",
        ),
        NigerianRecipe(
            "Dan Wake",
            ["beans flour", "flour", "potash", "pepper", "onion", "vegetable oil"],
            [
                "Mix beans flour, flour, potash, and water into a dough.",
                "Drop small pieces into boiling water.",
                "Cook until they float and become firm.",
                "Serve with pepper, onion, and oil.",
            ],
            "Breakfast/Lunch",
            "Medium",
        ),
        NigerianRecipe(
            "Eba",
            ["garri", "water"],
            [
                "Boil water in a pot.",
                "Pour garri into the hot water gradually.",
                "Stir until it becomes smooth and firm.",
                "Serve with any soup.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Semovita Swallow",
            ["semovita", "water"],
            [
                "Boil water in a pot.",
                "Pour semovita gradually while stirring.",
                "Keep stirring until smooth and firm.",
                "Serve with soup.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Pounded Yam",
            ["pounded yam flour", "water"],
            [
                "Boil water in a pot.",
                "Add pounded yam flour gradually.",
                "Stir until smooth and stretchy.",
                "Serve with egusi, ogbono, or vegetable soup.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        QuickRecipe(
            "Noodles and Egg",
            ["noodles", "egg", "onion", "pepper", "vegetable oil"],
            [
                "Boil the noodles with seasoning.",
                "Fry onion and pepper in vegetable oil.",
                "Add egg and scramble it.",
                "Mix with the cooked noodles.",
                "Serve hot.",
            ],
            "Breakfast/Lunch",
            "Easy",
        ),
        NigerianRecipe(
            "Yam and Egg Sauce",
            ["yam", "egg", "tomato", "onion", "pepper", "vegetable oil"],
            [
                "Boil sliced yam until soft.",
                "Fry tomato, onion, and pepper in vegetable oil.",
                "Add beaten eggs and stir gently.",
                "Serve the sauce with yam.",
            ],
            "Breakfast/Lunch",
            "Easy",
        ),
        NigerianRecipe(
            "Fried Plantain and Egg",
            ["plantain", "egg", "vegetable oil", "tomato", "onion", "pepper"],
            [
                "Slice and fry the plantain until golden brown.",
                "Fry tomato, onion, and pepper.",
                "Add beaten egg and stir.",
                "Serve the egg with fried plantain.",
            ],
            "Breakfast/Lunch",
            "Easy",
        ),
        NigerianRecipe(
            "Nigerian Beef Stew",
            ["beef", "tomato", "pepper", "onion", "vegetable oil", "seasoning", "salt"],
            [
                "Boil beef with onion, seasoning, and salt.",
                "Blend tomato, pepper, and onion.",
                "Fry the blend in vegetable oil until thick.",
                "Add beef and stock.",
                "Cook until the stew is ready.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Chicken Stew",
            ["chicken", "tomato", "pepper", "onion", "vegetable oil", "seasoning", "salt"],
            [
                "Boil chicken with onion, seasoning, and salt.",
                "Blend tomato and pepper.",
                "Fry the blend in vegetable oil.",
                "Add the chicken and stock.",
                "Cook until the stew thickens.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Groundnut Soup",
            ["groundnut", "palm oil", "fish", "crayfish", "pepper", "onion", "ugu"],
            [
                "Blend roasted groundnut into a paste.",
                "Cook fish with onion, pepper, and seasoning.",
                "Add groundnut paste, palm oil, and crayfish.",
                "Simmer until thick.",
                "Add ugu and serve with swallow.",
            ],
            "Lunch/Dinner",
            "Medium",
        ),
        NigerianRecipe(
            "Rice and Beans",
            ["rice", "beans", "onion", "pepper", "tomato", "vegetable oil"],
            [
                "Boil beans until partly soft.",
                "Add rice and continue cooking.",
                "Fry tomato, pepper, and onion in vegetable oil.",
                "Mix the sauce with the rice and beans.",
                "Cook until soft and serve.",
            ],
            "Lunch/Dinner",
            "Easy",
        ),
        NigerianRecipe(
            "Pap and Akara",
            ["pap", "beans", "pepper", "onion", "salt", "vegetable oil"],
            [
                "Prepare pap with hot water and stir until smooth.",
                "Blend peeled beans with pepper and onion.",
                "Add salt and fry the bean paste in oil.",
                "Serve the akara with pap.",
            ],
            "Breakfast",
            "Medium",
        ),
    ]

